# Generated by Django 5.1.6 on 2025-02-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='cubuceta', max_length=100),
            preserve_default=False,
        ),
    ]
